### ISSUE TITLE
Extract `SyntaxError` position comparison as a utility.

### ISSUE THREAD

**Issue by almann** [partiql/partiql-lang-rust#16]
We have code that wants to assert that a some error happened at some position, we should write a function to do this versus forcing the pattern matching boilerplate at the call site.

---

Similar to the other code--this probably suggests we should extract this out now that I think about it.

_Originally posted by @almann in https://github.com/partiql/partiql-lang-rust/pull/15#discussion_r630733972_

**Comment by almann** [comment]
No matter what we do for #18, we probably want some kind of utility to do this.  E.g.

```rust
fn eq_without_message(&self, other: &ParserError) -> bool { ... }
```

**Comment by jpschorr** [comment]
I actually think this is rather ergonomically possible today in a more general manner with:

```rust
assert!(matches!(
    error,
    ParserError::syntax_error(_, Position::at(12, 3))
)
```
