### ISSUE TITLE
Promote Delimiters/Operators in `scanner::Content` to Enum/Enum Variants

### ISSUE THREAD

**Issue by almann** [partiql/partiql-lang-rust#31]
#30 adds scanner tokens for various punctuation.  We have first-class variants for `Dot`/`Star`/`Parameter`, but `Delimiter` and `Operator` have the string of the token as their content.  It probably makes sense to lift this into either their own nested enums, or their own top-level variants.

**Comment by jpschorr** [comment]
Addressed by by #59
