### ISSUE TITLE
Partial timestamp support

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-rust#346]
According to [this comment](https://github.com/partiql/partiql-lang-rust/blob/59e78f12b09f487d9db70e851adf0682cca98a56/partiql-value/src/lib.rs#L52) timestamps aren't supported yet.  Let's change that.

Since my team isn't using PartiQL Rust's parser and are instead interfacing directly with the IR, and we have a very specific use-case for timestamps, full support for timestamps is not required.

Here's the minimal subset of timestamp support that my team needs that I am currently aware of:

- A representation in `enum Value` for timestamps with at *least* microsecond precision.
- Support for using timestamps in `=` and `<=` operators.

At this time, my team does not need:

- Support for timestamps in the parser.
- Functions to manipulate timestamps (e.g. `to_timestamp`, `date_add`, etc)
- The ability to represent timestamps with arbitrary precision.

Which will hopefully make this request relatively bite-sized.

**Comment by alancai98** [comment]
> According to [this comment](https://github.com/partiql/partiql-lang-rust/blob/59e78f12b09f487d9db70e851adf0682cca98a56/partiql-value/src/lib.rs#L52) timestamps aren't supported yet. Let's change that.

We currently have support for timestamps as of the v0.3.0 release: https://github.com/partiql/partiql-lang-rust/blob/380f5265feab34da02e933dff47b7845945f0699/partiql-value/src/lib.rs#L51 Perhaps you were looking at an older version of `partiql-lang-rust`?

> * A representation in `enum Value` for timestamps with at _least_ microsecond precision.
> * Support for using timestamps in `=` and `<=` operators.

The current time and timestamp values support precision of nanosecond and have an `impl`/derived implementation for `=` and `<=` operators.

Regarding your other points, 
- We are working to add support for timestamps in the parser through #345. You can already add parse Ion timestamps in the parser with the backticks
- We plan to add some more datetime-related functions. Are there any you think you'll need in particular?
- We haven't yet started representing timestamps with arbitrary precision

**Comment by dlurton** [comment]
Oh, well, I guess I stand corrected!  Didn't realize my local copy was out so of date.  😳 Thanks.
