### ISSUE TITLE
Conversion from ion_rs::element::Element to partiql_value::Value.

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-rust#351]
In my partiql application I need to convert `ion_rs::element::Element` to a `partiql_value::Value`, but no such functionality is directly provided for this.

The closest thing today is `partiql_value::parse_ion`, but that function only accepts a `&str`, so I am left with converting the `Element` to a string and then calling `parse_ion`.  This works, but is sub-optimal for obvious reasons.

This API should *not* panic and should always return `Result::Err` when possible.

**Comment by jpschorr** [comment]
This should become trivially implementable as an alternative input once the ion-rust exposes `ElementStreamReader`: https://github.com/amazon-ion/ion-rust/issues/547

**Comment by jpschorr** [comment]
Should be straightforward to extend [ion decode](https://github.com/partiql/partiql-lang-rust/blob/main/extension/partiql-extension-ion/src/decode.rs) based on https://github.com/amazon-ion/ion-rust/pull/563
