### ISSUE TITLE
When fed invalid Ion text, partiql_value::parse_ion panics instead of returning an Err

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-rust#352]
In my partiql application, we would like to be able to gracefully handle the case where our user has fed us malformed ion, but the [`parse_ion` function](https://github.com/partiql/partiql-lang-rust/blob/aa107b605f1a61054a989a5fc4bc3211e54d77b6/partiql-value/src/ion.rs#LL16C1-L16C1) panics instead.

**Comment by alancai98** [comment]
Related to https://github.com/partiql/partiql-lang-rust/issues/349.
