### ISSUE TITLE
Add API to convert `partiql_value::Value` to `ion_rs::element::Element`

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-rust#357]
This API serves the case for customers who need to work with the result of a query in memory instead of writing it to a stream.

Related to #356.

**Comment by jpschorr** [comment]
Similar to #351, this is probably best handled by adding an 'ElementStreamWriter' to ion rust and using that.

**Comment by jpschorr** [comment]
Should be straightforward to extend [ion encode](https://github.com/partiql/partiql-lang-rust/blob/main/extension/partiql-extension-ion/src/encode.rs) based on https://github.com/amazon-ion/ion-rust/pull/563
