### ISSUE TITLE
Migrate CI code coverage off nightly rust to stable

### ISSUE THREAD

**Issue by jpschorr** [partiql/partiql-lang-rust#364]
Cf. https://github.com/amazon-ion/ion-rust/pull/538 :

> Removes pin to nightly and removes the old -Zprofile runs and grcov based coverage generation in favor of -C source-instrumentation which is in stable.
> 
> This updates the CI to install llvm-tools-preview from rustup and install a nice wrapper for running source instrumentation called [cargo-llvm-cov](https://crates.io/crates/cargo-llvm-cov). We use this wrapper to generate codecov JSON to get region coverage since LCOV style output from source coverage in Rust/LLVM doesn't output branch coverage.

**Comment by alancai98** [comment]
Closed by #383.
