### ISSUE TITLE
Change some invalid Cargo.toml category slugs

### ISSUE THREAD

**Issue by alancai98** [partiql/partiql-lang-rust#379]
For some crates, we have the category slug "ast-implementations". this is currently being ignored since it is not in the list of category slugs in crates.io (see [list](https://crates.io/category_slugs)):
```
warning: the following are not valid category slugs and were ignored: ast-implementations. Please see https://crates.io/category_slugs for the list of all category slugs. 
```

Applies to:
- `partiql-ast-macros` -- https://github.com/partiql/partiql-lang-rust/blob/fe2dbee030f3b7b8a023ef648a3b30f01c3264f8/partiql-ast/partiql-ast-macros/Cargo.toml#L10
- `partiql-ast` -- https://github.com/partiql/partiql-lang-rust/blob/fe2dbee030f3b7b8a023ef648a3b30f01c3264f8/partiql-ast/Cargo.toml#L10

**Comment by jpschorr** [comment]
Fixed in #479
