### ISSUE TITLE
`partiql_value::Value` variant boxing

### ISSUE THREAD

**Issue by rajivr** [partiql/partiql-lang-rust#441]
`partiql_value::Value` is [defined](https://github.com/partiql/partiql-lang-rust/blob/febf4545004f13d5f462aa4b88312cf0382e2208/partiql-value/src/lib.rs#L41-L56) as follows.

```rust
pub enum Value {
    Null,
    #[default]
    Missing,
    Boolean(bool),
    Integer(i64),
    Real(OrderedFloat<f64>),
    Decimal(Box<RustDecimal>),
    String(Box<String>),
    Blob(Box<Vec<u8>>),
    DateTime(Box<DateTime>),
    List(Box<List>),
    Bag(Box<Bag>),
    Tuple(Box<Tuple>),
    // TODO: add other supported PartiQL values -- sexp
}
```

I was wondering if there was any specific reason for boxing the `Decimal`, `String`, `Blob` and `DataTime` variants?

**Comment by jpschorr** [comment]
See https://github.com/partiql/partiql-lang-rust/pull/411 for some minor explanation

In short, having a `Value` be as small as possible aids in data locality 

See the corresponding performance improvement from the benchmarks:
![image](https://github.com/partiql/partiql-lang-rust/assets/36067/7ab106ca-eb55-47f8-a4dc-55c253909e97)

**Comment by rajivr** [comment]
I see. Thanks for the reply!
